version: '3.8'

services:
  app:
    build: .
    image: e-commerce  # Tu imagen de la aplicación
    container_name: ecommerce-app
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db  # Aquí usamos el nombre del servicio "db" como el host
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "3000:3000"  # Exponer el puerto de tu aplicación

volumes:
  postgres_data:  # Volumen persistente para la base de datos

